version: "3"
services:
    client:
        container_name: shortly-client
        build:
            context: .
        volumes:
            - .:/app/
            - /app/node_modules
            - /app/build
        ports:
            - 3000:3000
        command: npm run dev
