version: "3"
services:
    client:
        container_name: shortly-client
        restart: on-failure
        build:
            context: ./client
        ports:
            - 3000:3000
    api:
        depends_on:
            - mongo
            - redis
        container_name: shortly-api
        restart: on-failure
        build:
            context: ./server
        #environment:
            #- DB=${DB}
            #- FRONT=${FRONT}
            #- PORT=${PORT}
        volumes:
            - ./server/.env:/app/.env # building the .env file into a docker image is considered a bad practice because if the image is shared with others, the secrets can be leaked.
        ports:
            - 3001:3001
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db # Make data persist in prod
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"] # Make data persist
        volumes:
            - ./data/redis:/data/redis
