version: "3"
services:
    client:
        container_name: shortly-client
        build:
            context: ./client
        ports:
            - 3000:3000
        command: npm start
    api:
        depends_on:
            - mongo
        container_name: shortly-api
        restart: on-failure
        build:
            context: ./server
        #environment:
            #- DB=${DB}
            #- FRONT=${FRONT}
            #- PORT=${PORT}
        ports:
            - 3001:3001
        command: npm start
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - /data/db:data/db # Make data persist in prod
